// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbcPY-Binv_-zPbGnGQBXmmq7PgUa1rsQ',
    appId: '1:173006370353:web:7460c2b0a28a8586258710',
    messagingSenderId: '173006370353',
    projectId: 'chat-app-2f657',
    authDomain: 'chat-app-2f657.firebaseapp.com',
    storageBucket: 'chat-app-2f657.firebasestorage.app',
    measurementId: 'G-3VRKE09DRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq2yNsqVC6tEcX8215iRa0uj9Hi6hkjS4',
    appId: '1:173006370353:android:b441ee7f03f45945258710',
    messagingSenderId: '173006370353',
    projectId: 'chat-app-2f657',
    storageBucket: 'chat-app-2f657.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABm1ae9_aXYZMUZ5Ju2z73KUtovw-y-ck',
    appId: '1:173006370353:ios:654ee583d5be573f258710',
    messagingSenderId: '173006370353',
    projectId: 'chat-app-2f657',
    storageBucket: 'chat-app-2f657.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABm1ae9_aXYZMUZ5Ju2z73KUtovw-y-ck',
    appId: '1:173006370353:ios:654ee583d5be573f258710',
    messagingSenderId: '173006370353',
    projectId: 'chat-app-2f657',
    storageBucket: 'chat-app-2f657.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbcPY-Binv_-zPbGnGQBXmmq7PgUa1rsQ',
    appId: '1:173006370353:web:419deac7877acd0c258710',
    messagingSenderId: '173006370353',
    projectId: 'chat-app-2f657',
    authDomain: 'chat-app-2f657.firebaseapp.com',
    storageBucket: 'chat-app-2f657.firebasestorage.app',
    measurementId: 'G-60JNYGJDTX',
  );
}
